columns:
  - id: int
  - age: int
  - gender: int
  - driving_experience: category
  - education: category
  - income: category
  - credit_score: float
  - vehicle_ownership: int
  - vehicle_year: category
  - married: int
  - children: int
  - postal_code: int
  - annual_mileage: float
  - speeding_violations: int
  - past_accidents: int
  - outcome: int


numerical_columns:
  - age
  - gender
  - credit_score
  - vehicle_ownership
  - married
  - children
  - postal_code
  - annual_mileage
  - speeding_violations
  - past_accidents
  - outcome


categorical_columns:
  - driving_experience
  - education
  - income
  - vehicle_year

ordinal_features:
  - driving_experience
  - education
  - income

onehot_features:
  - vehicle_year

drop_columns:
  - id
  - postal_code

# missing value columns
impute_features:
  - credit_score
  - annual_mileage

target_column:
  - outcome